### ISSUE TITLE
Pre-trained model on body

### ISSUE THREAD

**Issue by Tetsujinfr** [NVIDIA/vid2vid#11]
Do you provide a pre-trained model on pose to body estimation testing or we have to generate dataset and train one necessarily ?

**Comment by tcwang0509** [comment]
I'm not sure if we can release that model, since it contains personal information not in a public dataset. I'll need to check with the lawyers. Sorry for the inconvenience and thanks for your understanding.

**Comment by Tetsujinfr** [comment]
Thanks for your reply. Btw, would the trained model be generic enough? I am under the impression it is very apecific to your training data and may then not be useful unless I train my own model. Maybe I am not clear enough about the workflow for thia use case.

**Comment by tcwang0509** [comment]
Yes, if you want a different character, you need to train your own model.
