### ISSUE TITLE
Error in the function _init_params in models.py and update_learning_rate in base_model.py

### ISSUE THREAD

**Issue by bansals888** [NVIDIA/vid2vid#118]
![Screenshot (7)](https://user-images.githubusercontent.com/39440065/60582646-da0e1a00-9da6-11e9-95b4-b63cb9450686.png)
There are following two problems with this function:-
(1)-In the function init_params it should also get a parameter "data_loader" as when then condition ( ( (start_epoch > opt.niter_step) is encountered it will give an error. So we should also pass "data_loader" as parameter from train.py
(2)- When the condition (start_epoch > opt.niter) is encountered it will call "update_learning_rate" 
![Screenshot (9)](https://user-images.githubusercontent.com/39440065/60583377-610fc200-9da8-11e9-95f5-e20138882bd1.png)

which is using only "optimizer_D" so it is giving an error. So there should be two update_learning_rate each for Generator and Discriminator.
Can @tcwang0509 confirm it?

**Comment by tcwang0509** [comment]
Sorry for the errors. It should be fixed now. Thanks!
