### ISSUE TITLE
RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:88'

### ISSUE THREAD

**Issue by moshifengyan** [NVIDIA/vid2vid#17]
Hello!When I set the gpu_ids as '0,1' ,the program will throw the error.Who can help me?

**Comment by tcwang0509** [comment]
What's the complete command you ran?

**Comment by moshifengyan** [comment]
Thanks for your reply！I just add “--gpu_ids 0，1”into  train_256_g1.sh and then ran it

发自我的 iPhone

**Comment by pshah123** [comment]
This is usually returned when it cannot find the device, what is the output of the below:
``` bash
python -c "import torch; torch.cuda.set_device(1)"
```

If this also shows `invalid device ordinal` try checking `nvidia-smi` to see if there is more than 1 GPU device.

**Comment by Eyshika** [comment]
getting same problem @pshah123  output is : `python -c "import torch; torch.cuda.set_device(1)"`

**Comment by Usmaniatech** [comment]
If I use 

> torch.cuda.set_device(0)

it don't give any error, as it is set at index 0 but if I try

> torch.cuda.set_device(1)

it shows error

> THCudaCheck FAIL file=torch/csrc/cuda/Module.cpp line=32 error=10 : invalid device ordinal
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\muhammad.usman\AppData\Local\Continuum\anaconda3\envs\ml-agents\lib\site-packages\torch\cuda\__init__.py", line 262, in set_device
>     torch._C._cuda_setDevice(device)
> RuntimeError: cuda runtime error (10) : invalid device ordinal at torch/csrc/cuda/Module.cpp:32
