### ISSUE TITLE
Unexpected EOF using flownet download scripts

### ISSUE THREAD

**Issue by robbiebarrat** [NVIDIA/vid2vid#18]
so I've run `scripts/download_flownet2.py` with no errors, and satisfied the dependencies from the flownet github repo - but I'm still getting a flownet-related error when I try and train a vid2vid network. It claims that the file "models/flownet2_pytorch/FlowNet2_checkpoint.pth.tar" is corrupt.

My `FlowNet2_checkpoint.pth.tar` file is 48.6 MB (48,562,176 bytes) - is this the right size? my archive manager is having trouble opening it, so I'd assume that somehow it's corrupt.

Would *really* appreciate some help... maybe could someone link me to a version of this file that i can just download normally (minus scripts)?

Thanks so much for reading - the original error is here:

```Traceback (most recent call last):
  File "train.py", line 273, in <module>
    train()
  File "train.py", line 31, in train
    modelG, modelD, flowNet = create_model(opt)
  File "/home/beef/vid2vid/models/models.py", line 22, in create_model
    flowNet.initialize(opt)        
  File "/home/beef/vid2vid/models/flownet.py", line 19, in initialize
    checkpoint = torch.load('models/flownet2_pytorch/FlowNet2_checkpoint.pth.tar')
  File "/home/beef/.conda/envs/pytorch4/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/home/beef/.conda/envs/pytorch4/lib/python3.6/site-packages/torch/serialization.py", line 476, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_is_real_file)
RuntimeError: unexpected EOF. The file might be corrupted.```

**Comment by robbiebarrat** [comment]
EDIT: I found a download of a file named the exact same thing here: https://drive.google.com/uc?id=1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da&export=download

will update with how it goes in ~20 minutes after i download it. my internet sucks.

**Comment by robbiebarrat** [comment]
It worked!! My network is well and training. Closing this issue since that fixed the problem.

**Comment by cyremur** [comment]
For me the file `FlowNet2_checkpoint.pth.tar` wasn't even created after running `scripts/download_flownet2.py`. Thanks for providing the link, works like a charm.
