### ISSUE TITLE
Synthetic to Real video translation

### ISSUE THREAD

**Issue by mhusseinsh** [NVIDIA/vid2vid#21]
Hello,

Thanks for this amazing work. However, I have a question, can this model run on translating synthetic to real videos ? Let's say as the testing that was done for the UNIT network, from GTA5 to Cityscape for example

**Comment by tcwang0509** [comment]
The current framework only works on paired translations. However, some ideas should still be useful to the unpaired setting, like temporal discriminators, flow warping, etc.
