### ISSUE TITLE
Missing source code, face_dataset.py

### ISSUE THREAD

**Issue by fxfactorial** [NVIDIA/vid2vid#26]
As of bdb7ec6b60cd0d5f1c122aeebd4283e478d2d664, this repo is missing `face_dataset.py` which it appears should be in `data/face_dataset.py` 

as https://github.com/NVIDIA/vid2vid/blob/master/data/custom_dataset_data_loader.py#L11 implies it ought to exist and has been missing since first commit.

**Comment by tcwang0509** [comment]
duplicate of #24
