### ISSUE TITLE
Pose To Body To Be Used On Defined Body? 

### ISSUE THREAD

**Issue by rohit-shah** [NVIDIA/vid2vid#35]
Hey,

This is excellent work. I am curious, could I be able to use Pose to Body where I can define which body to use on? 

That is, say I could make myself dance in a video by giving the poses of some dancer. Is that possible? If so, please elaborate a little on how to achieve it. Also how many GPUs would be required for such a task. 

Thanks in advance!

**Comment by tcwang0509** [comment]
Yes that's basically how we did it. You need a video of yourself, train a model using this video, then apply this model on the extracted poses of a new video. Both 1 GPU and 8 GPU scripts are provided.

**Comment by rohit-shah** [comment]
> Yes that's basically how we did it. You need a video of yourself, train a model using this video, then apply this model on the extracted poses of a new video. Both 1 GPU and 8 GPU scripts are provided.

Excellent. A couple of questions. 

1) To train a model, how long should the video of me be? Also, does it need to be from all angles for better accuracy in results? That is, all parts of my body should be visible to accurately synthesis my body for poses?

2) What's the general time required to train a model (if the input video of me which for example is 4 mins long) with a single GPU? 

Thanks a lot again!

**Comment by tcwang0509** [comment]
1. We used about 3-4 mins, but longer should be better. Yes the more diverse the training set is the better.
2. On a single Volta it will probably take about 5-7 days.

**Comment by dimaxano** [comment]
@tcwang0509 How many 3-4 mins videos should be used to replicate your results?
