### ISSUE TITLE
Download scripts no longer working

### ISSUE THREAD

**Issue by fniroui** [NVIDIA/vid2vid#36]
> ModuleNotFoundError: No module named 'scripts.download_gdrive'

They need to be updated as the scripts are now in specific sub folders. Also, I believe an __init__.py file is required in the scripts folder.

**Comment by tcwang0509** [comment]
It seems I can run the script successfully without any issues. Can you provide more info of you system?

**Comment by fniroui** [comment]
Ubuntu 16.04, Python 3.6, PyTorch 0.4.0.
Tried both locally and on EC2. I'll keep looking to see if the problem is on my side, but adding the __init__.py file did fix the problem for me yesterday. 

> Traceback (most recent call last):
>   File "scripts/street/download_models.py", line 2, in <module>
>     from scripts.download_gdrive import *
> ModuleNotFoundError: No module named 'scripts.download_gdrive'

**Comment by rotten** [comment]
I am hitting the same error.  Ubuntu 18.04 Python 3.6.5.  My first reaction was to drop an __init__.py into the scripts folder too, but it didn't help on the first try.  I'm still looking at it.

**Comment by rotten** [comment]
My hack was to cd into scripts/street, then do "ln -s ../download_* .", and then update download_models.py to import from the current folder. Ditto for face and pose.  That is a hack, but it got me past that step for now. I was too impatient to figure out the correct import paths and module stubs.

**Comment by rohit-shah** [comment]
I am too having the same issue. I tried to run my own model and I am getting this: 

ImportError: No module named flownet2_pytorch.networks.resample2d_package.resample2d

This I think is because I was unable to download the sample model? Please help.

I am on ubuntu 16.04 running on 1 Tesla K80 GPU.

**Comment by fniroui** [comment]
> I am too having the same issue. Which is, I get this error when I try to download:
> 
> > ModuleNotFoundError: No module named 'scripts.download_gdrive'
> 
> I also tried to run my own model and I am getting this:
> 
> > ImportError: No module named flownet2_pytorch.networks.resample2d_package.resample2d
> 
> I have made sure pyTorch is installed. Its using 0.4.1.
> 
> This I think is because I was unable to download the sample model? Please help.
> 
> I am on ubuntu 16.04 running on 1 Tesla K80 GPU.

Hey rohit-shah, on a side note, are you able to train using K80 and pytorch 0.4.1?

**Comment by mrgloom** [comment]
Error still exist in master.

It's something like https://stackoverflow.com/questions/72852/how-to-do-relative-imports-in-python

**Comment by breckuh** [comment]
I forget Python's import rules so a quick hacky workaround is to insert this at the top of "scripts/face/download_models.py":

```
import sys
sys.path.insert(0, "Asbolute path to your vid2vid/scripts folder")
```

**Comment by TiborUdvari** [comment]
This error is also present when using the docker image

**Comment by sevmardi** [comment]
Having the same issue. Any proper ways to deal with this?

**Comment by htadashi** [comment]
> I forget Python's import rules so a quick hacky workaround is to insert this at the top of "scripts/face/download_models.py":
> 
> ```
> import sys
> sys.path.insert(0, "Asbolute path to your vid2vid/scripts folder")
> ```

breckuh solution works fine. Do not forget to change line:
 ```
from scripts.download_gdrive import *
 ```
to
 ```
from download_gdrive import *
 ```
