### ISSUE TITLE
Single GPU Pretrained face model not available?

### ISSUE THREAD

**Issue by petergerten** [NVIDIA/vid2vid#39]
I was looking for the single GPU face model.
Besides the `test_512.sh` script in the face directory, there are the following scripts:
```
test_g1_256.sh
test_g1_512.sh
```
If i understand correctly, those are for the single GPU models.
When downloading the models however I only get those directories:
```
edge2face_512
edge2face_single
```
I tried to rename the edge2face_single model directory but there is not the expected latest_net_G0.pth file but 3 files: 
```
features.npy
latest_net_E.pth
latest_net_G.pth

```
Any suggestions on how to make the single GPU face model work?

**Comment by tcwang0509** [comment]
Sorry for the confusion. edge2face_single is for **single image** (instead of video) edge2face translation, not a model trained on a single GPU. I haven't trained one on single GPU yet.

**Comment by mrgloom** [comment]
Is there example of usage for single image ?

**Comment by tcwang0509** [comment]
If you just want to do single image instead of videos, you can use our pix2pixHD repo: https://github.com/NVIDIA/pix2pixHD/
