### ISSUE TITLE
 vid2vid/data/face_dataset.py first image parameters

### ISSUE THREAD

**Issue by nwestlake** [NVIDIA/vid2vid#40]
In lines 32--34 of  vid2vid/data/face_dataset.py,
```
B_img = Image.open(B_paths[0]).convert('RGB')
B_size = B_img.size
points = np.loadtxt(A_paths[0], delimiter=',')
```
is there a reason why [0] is preferred over [start_idx]?

**Comment by tcwang0509** [comment]
Thanks for finding it. It will be updated in the next commit.
