### ISSUE TITLE
Which algorithm is used to generate train_A and train_inst?

### ISSUE THREAD

**Issue by forfun1012** [NVIDIA/vid2vid#45]
I want to use my urban street video to generate a video just like in your videos.
And can you share which segmentation algorithm is used as you describe in README.md?
"We apply a pre-trained segmentation algorithm to get the corresponding semantic maps (train_A) and instance maps (train_inst)."

**Comment by lorriexingfang** [comment]
Coask. Anybody could help on that?

**Comment by jiameij** [comment]
i have the same question, is there any response?

**Comment by JamesChenChina** [comment]
same question
