### ISSUE TITLE
Single image generator does not exist?

### ISSUE THREAD

**Issue by anubhav0fnu** [NVIDIA/vid2vid#46]
I tried to run test.py using shell scripts provided in ./scripts/street/* . The testing works fine on Cityscapes-test with 2048 & 1024 model in given configurations.

I changed the configurations a bit 
`python test.py --name label2city_2048 --label_nc 35 --loadSize 1024 --n_scales_spatial 3 --use_instance --fg --n_downsample_G 2 --use_single_G`

and try to understand if I change the --loadsize to 720or540 {which is not a multiple of 32} & even 1024 or 256 {which is a multiple of 32} What will be the outcome. Using the "label2city_2048" model, I am able use -loadsize: 1024, but code fails when I use 720or540or256 with error:

```
File "/home/ubuntu/Documents/anubhav/vid2vid/models/vid2vid_model_G.py", line 279, in load_single_G raise ValueError('Single image generator does not exist')
ValueError: Single image generator does not exist
```

**question.1 :** Could you please suggest me, why it's not working for another load size? and what could be a potential fix?

Furthermore, I was testing existing models on another dataset (BDD100K), My test-set images are (720*1280) instead of your's CityScapes(1024*2048). I used the "label2city_1024_g1" model, with the following conf.

`python test.py --name label2city_1024_g1 --dataroot datasets/BDD/ --label_nc 40 --loadSize 720 --n_scales_spatial 3 --n_downsample_G 2 --use_single_G
`it errors out 

`valueError: Single image generator does not exist
`
and without "--use_single_G" option it complains of 

`ValueError: Please specify the method for generating the first frame`

Then, I have used "--use_real_img" option which looks for 3-channel Semantic segmentation masked images in Test_B(I provided), then again it errors out :

`RuntimeError: invalid argument 2: size '[1 x -1 x 3 x 704 x 1280]' is invalid for input with 9011200 elements at /opt/conda/conda-bld/pytorch_1532579245307/work/aten/src/TH/THStorage.cpp:80  `

**My question 2 :** , Could you please suggest what I am doing wrong which doesn't conform with your code, especially your thoughts on the last error?

thanks in advance

@junyanz, @tcwang0509, @mingyuliutw

**Comment by nwestlake** [comment]
You would have to change the code (around models/vid2vid_model_G.py line 279) to permit these different sizes **and** retrain the model with these sizes.
