### ISSUE TITLE
Tests don't pass

### ISSUE THREAD

**Issue by karipulli** [NVIDIA/vid2vid#48]
These tests all fail:

bash ./scripts/street/test_2048.sh
-->
AssertionError: datasets/Cityscapes/test_A is not a valid directory

bash ./scripts/street/test_g1_1024.sh
-->
AssertionError: datasets/Cityscapes/test_A is not a valid directory

bash ./scripts/face/test_512.sh
-->
AssertionError: datasets/face/test_keypoints is not a valid directory

Downloading the datasets seems to be lower in the instructions, and optional.
Is it required?

**Comment by sunshinewhy** [comment]
Excuse me! When I run test_g1_1024, the terminal shows error that
assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: datasets/Cityscapes/test_A is not a valid directory
How to solve this problem? Thanks a lot!
