### ISSUE TITLE
Dockerfile not compatible with Tesla V100 

### ISSUE THREAD

**Issue by burnzzz** [NVIDIA/vid2vid#52]
The Dockerfile you provide is based on cuda 8.0 and cannot be used with current Tesla Cards because they need at least cuda 9.0. If you need the 32GB V100 to run the training effectively at full resolution, then there is a mismatch.

Will the code be updated to pytorch 1.0 in the future? pytorch 0.4.0 has problems with current cuda releases.

**Comment by dustinfreeman** [comment]
FYI, this "just worked" when I updated the docker: #67

**Comment by dustinfreeman** [comment]
FYI, this "just worked" when I updated the docker: #67

**Comment by dustinfreeman** [comment]
It "just worked" for me on V100 when I updated the Dockerfile like so: #67

**Comment by rmitsch** [comment]
Didn't work for me unfortunately, I had to go with P100s instead - see https://github.com/NVIDIA/vid2vid/issues/73.
