### ISSUE TITLE
Please add reference to docker in README.md

### ISSUE THREAD

**Issue by jprouty** [NVIDIA/vid2vid#54]
I was stumped trying to get all the right toolchains setup to be compatible with this project. BUT, after nearly giving up, I found there was a docker/ dir, and decided to check it out. The dockerfile + scripts are a life saver and got me setup in minutes with the right toolchain.

Please add a mention of this to the README so others know to look for it and how to get going much faster!

**Comment by tcwang0509** [comment]
Sorry for the confusion! It will get updated.
