### ISSUE TITLE
about the  parameter setting  in pose2pose train scripts

### ISSUE THREAD

**Issue by kekedan** [NVIDIA/vid2vid#56]
Hi，the parameters setting   in pose2pose train scripts is actual parameters in  your experiment, or just an example ? such as the  "--niter 5 --niter_decay 5  "  thank you !

**Comment by tcwang0509** [comment]
That is what I used for training a ~3 mins video. You can modify it based on your need.

**Comment by tcwang0509** [comment]
What do you mean by large movement? Like backflip? The motions will definitely be limited by the training video, no matter what algorithm you use.
Longer examples are already in our YouTube video.
