### ISSUE TITLE
The return tensor of CompositeGenerator don't match the tensor in train.py

### ISSUE THREAD

**Issue by donghaoye** [NVIDIA/vid2vid#57]
network.py line 199:         
return **img_final, flow, weight, img_raw, img_feat, flow_feat, img_fg_feat**

train.py       line 102:
**fake_B, fake_B_raw, flow, weight, real_A, real_Bp, fake_B_last** = modelG(input_A, input_B, inst_A, fake_B_last)

**Comment by tcwang0509** [comment]
Why do they need to match? modelG calls the generator network, but is not the network itself.

**Comment by donghaoye** [comment]
Sorry. I get it.
