### ISSUE TITLE
test.py: error: unrecognized arguments: --use_single_G

### ISSUE THREAD

**Issue by wygdkl** [NVIDIA/vid2vid#59]
Hello, I met this problem :"test.py: error: unrecognized arguments: --use_single_G" when I run the command:" bash ./scripts/street/test_2048.sh ".  
My enviroment is ubuntu16.04 with CUDA9.0, anaconda3(python3.6) and pytorch 0.4.1.  
GPU: 1 signle Nvidia TITAN X. 
Could anyone tell me how to solve this problem? Thanks a lot!

**Comment by wygdkl** [comment]
Well, I delete the "--use_instance --fg --use_single_G" in the  ./scripts/street/test_2048.sh, and the previously mentioned problem didn't show anymore.  But a new problem of "ValueError: Please specify the method for generating the first frame"  has arisen.  Could anyone help me? I will be very grateful to you.

**Comment by tcwang0509** [comment]
Are you sure you pulled the latest code and didn't make any modification? `use_single_G` is defined in `options/base_options.py`. Can you check if it's there?
