### ISSUE TITLE
scripts/street/download_models.py: Import Error

### ISSUE THREAD

**Issue by Bowenwu1** [NVIDIA/vid2vid#60]
Hello, I'm trying to run vid2vid and encounter  some weird problem.

When I run ` python scripts/street/download_models.py`,
It raise:
`
Traceback (most recent call last):
  File "scripts/street/download_models.py", line 4, in <module>
    from scripts.download_gdrive import *
ModuleNotFoundError: No module named 'scripts.download_gdrive'
`

I know this question might be stupid, but I'm stuck for a while.
Hope for your response! Thank You!

**Comment by wygdkl** [comment]
Hello, "scripts.download_gdrive" maybe means the python file :"vid2vid/scripts/download_gdrive.py", you should consider adding the path in download_models.py to solve this problem.

**Comment by Bowenwu1** [comment]
Thank you for your response!
I have checked `sys.path` before, and it outputs as follows:

![image](https://user-images.githubusercontent.com/16816766/47002284-22c16c80-d15f-11e8-97ad-9453a336227f.png)


As you can see, the path is already in `sys.path`.

But never mind this issue, I move `download_gdrive.py` to the same dir with `download_models.py` to solve the problem.

But I still think it's a potential bug.
