### ISSUE TITLE
Dataset size and epochs

### ISSUE THREAD

**Issue by nfrik** [NVIDIA/vid2vid#64]
1. Could you advise on how big of a dataset does one need in order to generate pose videos with the quality similar to what you published? I got 100 images, similar to the images in train folder, but the resulting frames are only a slight approximation of a human body.

2. By default train script runs with 10 epochs, which is the result of 5 niter and 5 niter_decay shift. I noticed that increasing niter to 15, produces even worse results. Do you have any recommendations on how to properly increase the number of epochs?

Thank you.

**Comment by tcwang0509** [comment]
You can't train anything with just 100 images. You need something in the order of 5k to 10k.
