### ISSUE TITLE
Have anyone tried to train on Google Colab? Or a single GPU

### ISSUE THREAD

**Issue by yuanzhou15** [NVIDIA/vid2vid#71]
I'm wondering what flags I should use when I'm trying to train the model on a single google colab gpu, because I'm currently running into memory problems. I know the readme suggests a few flags, but I'm wondering if anyone has successfully trained with just one GPU and what flags you've used.

**Comment by dimaxano** [comment]
I didn't trained on Colab GPUs, but I've trained on the one 1080ti, I used the same flags as README suggests. Everything was OK

**Comment by junyanz** [comment]
There is a CycleGAN project on Google [Colab](https://colab.research.google.com/drive/1Enc-pKlP4Q3cimEBfcQv0B_6hUvjVL3o?sandboxMode=true).

**Comment by sarrbranka** [comment]
https://github.com/sarrbranka/vid2vid_colab
